# Generated by Django 5.2.2 on 2025-06-09 14:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
