# Generated by Django 5.2.2 on 2025-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_alter_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkdownProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("markdown_file", models.FileField(upload_to="markdown_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
