# Generated by Django 5.2.2 on 2025-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdownproject",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
