# Generated by Django 5.2.2 on 2025-06-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_markdownproject_github_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdownproject",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of technologies (e.g. Python, Django, Bootstrap)",
                max_length=255,
            ),
        ),
    ]
