# Generated by Django 5.2.2 on 2025-06-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0006_markdownproject_tech_stack"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Short summary of your thought (for listing)"
                    ),
                ),
                ("markdown_file", models.FileField(upload_to="thoughts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
