# Generated by Django 5.2.2 on 2025-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0007_thought"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdownproject",
            name="description",
            field=models.TextField(blank=True, help_text="Short summary for list page"),
        ),
        migrations.AlterField(
            model_name="markdownproject",
            name="tech_stack",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
