# Generated by Django 5.2.2 on 2025-06-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0008_markdownproject_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markdownproject",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of technologies (e.g. Python, Django, Bootstrap)",
                max_length=255,
            ),
        ),
    ]
